paperworks/urls.py
from django.conf.urls import url, include

from django.conf import settings

from .views import PapermailList, PapermailDetail, PapermailCreate, PapermailUpdate, PapermailDelete, SenderCreate, RecipientCreate, PrivatePapermailMedia

from auxiliare import urls

urlpatterns = [
    url(r'^', include('auxiliare.urls')),
    url(r'^list/$', PapermailList.as_view(), name='papermail-list'),
    url(r'^(?P<pk>\d+)/$', PapermailDetail.as_view(), name='papermail-detail'),
    url(r'^create/$', PapermailCreate.as_view(), name='papermail-create'),
    url(r'^maj/(?P<pk>\d+)/$', PapermailUpdate.as_view(), name='papermail-update'),
    url(r'^delete/(?P<pk>\d+)/$', PapermailDelete.as_view(), name='papermail-delete'),
    url(r'^create-sender/$', SenderCreate.as_view(), name='sender-create'),
    url(r'^create-recipient/$', RecipientCreate.as_view(), name='recipient-create'),
    url(r'^download-papermail/(?P<pk>\d+)/$', PrivatePapermailMedia.as_view(), name='private-papermail-media'),
]

paperworks/models.py
from django.db import models
from django.db.models import signals
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from django.utils.deconstruct import deconstructible
from django.conf import settings

from wand.image import Image

import os
from uuid import uuid4

paperworks_media_root = getattr(settings, 'PAPERWORKS_MEDIA_ROOT','')

class Sender(models.Model):
    
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('papermail-list')

class Recipient(models.Model):
    
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('papermail-list')

class Tag(models.Model):
    
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name

@deconstructible
class PathAndRename(object):

    """Rename the file with uuid64 module"""

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
         # get filename
        if instance.pk:
            filename = '{}.{}'.format(instance.pk, ext)
        else:
            # set filename as random string
            filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
            return os.path.join(self.path, filename)
        return wrapper

path_and_rename = PathAndRename(paperworks_media_root)

class Papermail(models.Model):
    
    paper_file = models.FileField(upload_to = path_and_rename)
    name_file = models.CharField(max_length=200)
    thumbnail = models.ImageField(upload_to = paperworks_media_root, blank=True)
    sender = models.ForeignKey(Sender, on_delete=models.CASCADE)
    recipient = models.ForeignKey(Recipient, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag,blank=True)
    date_creation = models.DateTimeField(auto_now_add = True)
    date_modification = models.DateTimeField(auto_now = True)
    date_paper = models.DateField()
    property_of = models.ForeignKey(User, on_delete=models.CASCADE, related_name='paperwork_owner')
    shared_with = models.ManyToManyField(User, blank=True, related_name='paperwork_user')

    def __str__(self):
        return self.name_file
    
    def get_absolute_url(self):
        return reverse('papermail-detail', kwargs={'pk': self.pk})

paperworks/templates/paperworks/papermail_confirm_delete.html
{% load i18n %}
<div class='row' >
	<form action="{% url 'papermail-delete' papermail.id %}" method="post">
		{% csrf_token %}
		<p class="text-center">{% trans "Do you want to delete " %} {{ papermail.name_file }} ?</p>
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "I'm sure" %}">
		</p>
</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

paperworks/templates/paperworks/papermail_create_form.html
{% load i18n %}
<div class="row">
	<div class="success callout display_for_success" data-closable id="response_papermail">
		<p class="text-center">{% trans "Papermail" %} <span id="return_papermail"></span> {% trans "is created" %}</p>
	</div>
	<div class="alert callout display_for_success" data-closable id="error_create_papermail">
		<p class="text-center"><i class="fi-alert red-color"></i>{% trans "Papermail isn't created" %}  <i class="fi-alert red-color"></i></p>
	</div>
	<form action="" method="post" id="addPapermailSend" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			
			<input type="submit" class="button" value="{% trans "Submit" %}">  <button class='button' onclick="reloadPage()"> {% trans "It's over!" %}</button>
		</p>
	</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

	<script type="text/javascript">
		$(function(){
			$('#id_date_paper').fdatepicker({
				format: 'dd/mm/yyyy',
				disableDblClickSelection: true,
				language: navigator.language
			});
		});
	</script>

	<script type="text/javascript">
		$( '#addPapermailSend' )
			.submit( function( e ) {
				$.ajax( {
					success:  function(resp) {
						document.getElementById("return_papermail").innerHTML = resp.name_file;
						$("#response_papermail").show();
						setTimeout(function() {
							$("#response_papermail").hide();
							$('#addPapermailSend')[0].reset();
						}, 3000 );
					},
					error : function(xhr) {
						$("#error_create_papermail").show();
						setTimeout(function() {
							$("#error_create_papermail").hide();
						}, 4000 );
					},
					url: '{% url 'papermail-create' %}',
					type: 'POST',
					data: new FormData( this ),
					processData: false,
					contentType: false
				} );
				e.preventDefault();
				
			} );
	</script>
	<script type="text/javascript">
		function reloadPage() {
			location.reload();
		}
	</script>
	

paperworks/templates/paperworks/papermail_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block title %}{{ papermail.name_file }}{% endblock %}

{% block content %}
    <div class='column row margin-top'>
        <h2 class='text-center'>{{ papermail.name_file }}</h2>
    </div>
    <div class='row'>
        <div class='small-4 columns'>
            <img class='thumbnail' src="{% if papermail.thumbnail %}{{ papermail.thumbnail.url }}{% else %}{% static 'paperworks/images/default_thumb.jpg' %}{% endif %}"/>
        </div>
        <div class='small-8 columns'>
            <p>
                <div class="button-group show-for-medium">
                    <button class="button success" onClick="updatePapermail('{% url 'papermail-update' papermail.id %}')"><i class="fi-pencil"></i>{% trans "Update" %}</button>
                    <button class="button"><i class="fi-share"></i> {% trans "Share" %}</button>
                    <button class="alert button" onClick="deletePapermail('{% url 'papermail-delete' papermail.id %}')"><i class="fi-x"></i> {% trans "Delete" %}</button>
                </div>
				<div class="button-group hide-for-medium">
                    <button class="button success" onClick="updatePapermail('{% url 'papermail-update' papermail.id %}')"><i class="fi-pencil"></i></button>
                    <button class="button"><i class="fi-share"></i></button>
                    <button class="alert button" onClick="deletePapermail('{% url 'papermail-delete' papermail.id %}')"><i class="fi-x"></i></button>
                </div>
            </p>
            <p>{% trans "Papermail's Date" %} : {{ papermail.date_paper }} </p>
            <p>{% trans "Sender" %} : {{ papermail.sender }} </p>
			<p>{% trans "Recipient" %} : {{ papermail.recipient }} </p>
            <p>{% trans "Tags" %} : {% for tag in papermail.tag.all %}{{ tag.name }}{% if not forloop.last %} | {% endif %}{% endfor %}</p>
            <p><a href='{% url 'private-papermail-media' papermail.id %}' target="_blank" class='button'><i class="fi-download"></i> {% trans "Download" %}</a></p>
        </div>
    </div>

	<div class="reveal" id="PapermailUpdate" data-reveal data-multiple-opened="true">
	</div>
	<div class="reveal" id="PapermailDelete" data-reveal>
	</div>
	<div class="reveal" id="openSenderForm" data-reveal data-multiple-opened="true">
	</div>
	<div class="reveal" id="openRecipientForm" data-reveal data-multiple-opened="true">
	</div>
{% endblock %}

{% block javascript %}

	<script type="text/javascript">
		function updatePapermail($idPapermail) {
			$.ajax($idPapermail)
			.done(function(resp){
				$("#PapermailUpdate").html(resp).foundation('open');
			});
		}
	</script>
	
	<script type="text/javascript">
		function deletePapermail($idPapermail) {
			$.ajax($idPapermail)
		.done(function(resp){
			$("#PapermailDelete").html(resp).foundation('open');
		});
		}
	</script>
	<script type="text/javascript">
		function addSender() {
			$.ajax('{% url 'sender-create' %}')
			.done(function(resp){
				$("#openSenderForm").html(resp).foundation('open');
			});
		}
	</script>
	
	<script type="text/javascript">
		function addRecipient() {
			$.ajax('{% url 'recipient-create' %}')
			.done(function(resp){
				$("#openRecipientForm").html(resp).foundation('open');
			});
		}
	</script>
{% endblock %}

paperworks/templates/paperworks/papermail_form.html
{% load i18n %}
<div class="row">
	<div class="success callout display_for_success" data-closable id="response_papermail">
		<p class="text-center">{% trans "Papermail" %} <span id="return_papermail"></span> {% trans "is updated" %}</p>
	</div>
	<div class="alert callout display_for_success" data-closable id="error_update_papermail">
		<p class="text-center"><i class="fi-alert red-color"></i> {% trans "Papermail isn't updated" %} <i class="fi-alert red-color"></i></p>
	</div>
	<form action="" id='updatePapermailSend' method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "Submit" %}">
		</p>
	</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

	<script type="text/javascript">
		$(function(){
			$('#id_date_paper').fdatepicker({
				format: 'dd/mm/yyyy',
				disableDblClickSelection: true,
				language: navigator.language
			});
		});
	</script>

	<script type="text/javascript">
		$( '#updatePapermailSend' )
			.submit( function( e ) {
				$.ajax( {
					success:  function(resp) {
						document.getElementById("return_papermail").innerHTML = resp.name_file;
						$("#response_papermail").show();
						setTimeout(function() {
							$("#response_papermail").hide();
							location.reload();
						}, 2000 );
					},
					error : function(xhr) {
						$("#error_update_papermail").show();
						setTimeout(function() {
							$("#error_update_papermail").hide();
						}, 2000 );
					},
					url: '{% url 'papermail-update' papermail.id %}',
					type: 'POST',
					data: new FormData( this ),
					processData: false,
					contentType: false
				} );
				e.preventDefault();
				
			} );
	</script>

paperworks/templates/paperworks/papermail_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block title %}{% trans "List of files" %}{% endblock %}

{% block content %}
        <div class='row margin-bottom margin-top'>
			<div class='small-6 columns'>
				<p class="text-center show-for-medium"><button class='button' onClick="addPapermail()">{% trans "Add a papermail" %} <i class="fi-plus"></i></button></p>
				<p class="text-center hide-for-medium"><button class='button' onClick="addPapermail()"><i class="fi-plus"></i></button></p>
			</div>
			<div class='small-6 medium-4 columns'>
					<div class="small button-group show-for-medium">
							<a class="button" onClick="changePapermailView('details')"><i class="fi-list-thumbnails"></i> {% trans "Details" %}</a>
							<a class="button" onClick="changePapermailView('list')"><i class="fi-list"></i> {% trans "List" %}</a>
							<a class="button" onClick="changePapermailView('mosaic')"><i class="fi-thumbnails"> {% trans "Mosaic" %}</i></a>
					</div>
					<div class="small button-group hide-for-medium">
							<a class="button" onClick="changePapermailView('details')"><i class="fi-list-thumbnails"></i></a>
							<a class="button" onClick="changePapermailView('list')"><i class="fi-list"></i></a>
							<a class="button" onClick="changePapermailView('mosaic')"><i class="fi-thumbnails"></i></a>
					</div>
			</div>
        </div>
<span id="papermail_view">
 {% include request.session.fileview %}
</span>

<div class="reveal" id="addPapermailForm" data-reveal data-multiple-opened="true">
</div>

<div class="reveal" id="openSenderForm" data-reveal data-multiple-opened="true">
</div>

<div class="reveal" id="openRecipientForm" data-reveal data-multiple-opened="true">
</div>

<!-- pagination -->
	{% if is_paginated %}
	<div class="row">
		<ul class="pagination text-center" role="navigation" aria-label="Pagination">
			{% if page_obj.has_previous %}
				<li class="pagination-previous"><a href="{% url 'papermail-list' %}?page={{ page_obj.previous_page_number }}" aria-label="Previous page"><i class="fi-previous"></i></a></li>
				<li><a href="{% url 'papermail-list' %}?page={{ page_obj.paginator.page_range|first }}" aria-label="Page {{ page_obj.paginator.page_range|first }}">{{ page_obj.paginator.page_range|first }}</a></li>
			{% else %}
				<li class="pagination-previous disabled"><i class="fi-previous"></i></li>
			{% endif %}
				{% for page in page_obj.paginator.page_range %}
					{% if page == page_obj.number %}
						<li class="current">{{ page_obj.number }}</li>
					{% elif page == page_obj.paginator.page_range|first %}
					{% elif page == page_obj.paginator.page_range|last %}
					{% elif page == page_obj.number|add:"4" or page == page_obj.number|add:"-4" %}
						<li class="ellipsis"></li>
					{% elif page > page_obj.number|add:"4" or page < page_obj.number|add:"-4" %}
					{% else %}
						<li><a href="{% url 'papermail-list' %}?page={{ page }}" aria-label="Page {{ page }}">{{ page }}</a></li>
					{% endif %}
				{% endfor %}
			{% if page_obj.has_next %}
				<li><a href="{% url 'papermail-list' %}?page={{ page_obj.paginator.page_range|last }}" aria-label="Page {{ page_obj.paginator.page_range|last }}">{{ page_obj.paginator.page_range|last }}</a></li>
				<li class="pagination-next"><a href="{% url 'papermail-list' %}?page={{ page_obj.next_page_number }}" aria-label="Next page"><i class="fi-next"></i></a></li>
			{% else %}
				<li class="pagination-next disabled"><i class="fi-next"></i></li>
			{% endif %}
		</ul>
	</div>		
	{% endif %}
<!-- fin de la pagination -->
{% endblock %}

{% block javascript %}

    <script type="text/javascript">
		function changePapermailView(action){
			$.ajax({
				url:'{% url 'papermail-list' %}?page={{ page_obj.number }}',
				data: {action: action},
				dataType: "html",
				type: 'GET',
				success: function(data){
					$("#papermail_view").empty().hide();
					$("#papermail_view").append(data);
					$('#papermail_view').fadeIn(2000);
					}
				});
		}
	</script>
	<script type="text/javascript">
		function addPapermail() {
			$.ajax('{% url 'papermail-create' %}')
			.done(function(resp){
				$("#addPapermailForm").html(resp).foundation('open');
			});
		}
	</script>

	<script type="text/javascript">
		function addSender() {
			$.ajax('{% url 'sender-create' %}')
			.done(function(resp){
				$("#openSenderForm").html(resp).foundation('open');
			});
		}
	</script>

	<script type="text/javascript">
		function addRecipient() {
			$.ajax('{% url 'recipient-create' %}')
			.done(function(resp){
				$("#openRecipientForm").html(resp).foundation('open');
			});
		}
	</script>

{% endblock %}

paperworks/templates/paperworks/recipient_create_form.html
{% load i18n %}
<div class="row">
	<div class="success callout display_for_success" data-closable id="response_recipient">
		<p class="text-center">{% trans "Recipient" %} <span id="return_recipient"></span> {% trans "is created" %}</p>
	</div>
	<div class="alert callout display_for_success" data-closable id="error_create_recipient">
		<p class="text-center"><i class="fi-alert red-color"></i> {% trans "Recipient isn't created" %} <i class="fi-alert red-color"></i></p>
	</div>
	<form action="" id="addRecipientSend" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "Submit" %}">
		</p>
	</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

<script type="text/javascript">
	$( '#addRecipientSend' )
		.submit( function( e ) {
			$.ajax( {
				success:  function(resp){
					document.getElementById("return_recipient").innerHTML = resp.name;
					$("#response_recipient").show();
					setTimeout(function() {
						$("#response_recipient").hide();
						$("#id_recipient").append('<option value="'+ resp.pk +'" selected="selected">'+ resp.name + '</option>');
						$("#openRecipientForm").html(resp).foundation('close');
					}, 3000 );
				},
				error : function(xhr) {
					$("#error_create_recipient").show();
					setTimeout(function() {
						$("#error_create_recipient").hide();
					}, 4000 );
				},
				url: '{% url 'recipient-create' %}',
				type: 'POST',
				data: new FormData( this ),
				processData: false,
				contentType: false
			} );
			e.preventDefault();
			
		} );
</script>

paperworks/templates/paperworks/sender_create_form.html
{% load i18n %}
<div class="row">
	<div class="success callout display_for_success" data-closable id="response_sender">
		<p class="text-center">{% trans "Sender" %} <span id="return_sender"></span> {% trans "is created" %}</p>
	</div>
	<div class="alert callout display_for_success" data-closable id="error_create_sender">
		<p class="text-center"><i class="fi-alert red-color"></i> {% trans "Sender isn't created" %} <i class="fi-alert red-color"></i></p>
	</div>
	<form action="" id="addSenderSend" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			<input type="submit" class="button" value="{% trans "Submit" %}">
		</p>
	</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

<script type="text/javascript">
	$( '#addSenderSend' )
		.submit( function( e ) {
			$.ajax( {
				success:  function(resp){
					document.getElementById("return_sender").innerHTML = resp.name;
					$("#response_sender").show();
					setTimeout(function() {
						$("#response_sender").hide();
						$("#id_sender").append('<option value="'+ resp.pk +'" selected="selected">'+ resp.name + '</option>');
						$("#openSenderForm").html(resp).foundation('close');
					}, 3000 );
				},
				error : function(xhr) {
					$("#error_create_sender").show();
					setTimeout(function() {
						$("#error_create_sender").hide();
					}, 4000 );
				},
				url: '{% url 'sender-create' %}',
				type: 'POST',
				data: new FormData( this ),
				processData: false,
				contentType: false
			} );
			e.preventDefault();
			
		} );
</script>